#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one stage() per step the human takes; TOTAL_STAGES counts them.
# ──────────────────────────────────────────────────────────────────────────
#
# Sets up the fixture Projects (docs/fixtures.md): the organisations, groups,
# GitHub App and tokens only a person can make, then seeds the Fixtures with
# your own `gh` and `glab` login. Run it from the repository's checkout.
# Secrets go only to this repository's GitHub Actions secrets; the few
# public values it remembers are kept outside the repository.

TOTAL_STAGES=9

# Nothing is written inside the repository, which is headed public.
ENV_FILE="${ENV_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/issue-map/fixtures.env}"
mkdir -p "$(dirname "$ENV_FILE")"

# The namespaces test/live/fixtures.ts declares; renaming one is an edit there.
eval "$(node test/live/fixtures.ts names)"

banner "issue-map fixture Projects"

stage "GitHub — two organisations"
say "The GitHub Fixtures live in two organisations the project owns, never a personal account."
say "Make each one on the Free plan, owned by the project (not by a person's name)."
open_url "https://github.com/account/organizations/new?plan=free"
step "Organization name: ${BOLD}${GH_MAIN}${RESET}. Then make a second one: ${BOLD}${GH_OTHER}${RESET}."
note "If a name is taken, pick another and change NAMESPACES.github in test/live/fixtures.ts to match."
pause "Press Enter once both organisations exist"

stage "GitHub — register the reading App"
say "CI reads the GitHub Fixtures as a GitHub App, never a personal login."
open_url "https://github.com/organizations/${GH_MAIN}/settings/apps/new"
step "GitHub App name: issue-map-fixtures-reader (or any free name). Homepage URL: this repository's URL."
step "Webhook: untick ${BOLD}Active${RESET}."
step "Repository permissions: ${BOLD}Issues: Read-only${RESET}, ${BOLD}Pull requests: Read-only${RESET}; Metadata stays Read-only. Nothing else."
step "Where can this GitHub App be installed? ${BOLD}Any account${RESET}, so it can be installed on ${GH_OTHER} too."
step "Create GitHub App. On its General page, copy the ${BOLD}Client ID${RESET}."
ask FIXTURES_APP_CLIENT_ID "Paste the Client ID:"
write_env FIXTURES_APP_CLIENT_ID "$FIXTURES_APP_CLIENT_ID"
set_var FIXTURES_APP_CLIENT_ID "$FIXTURES_APP_CLIENT_ID"
step "Further down, Private keys → ${BOLD}Generate a private key${RESET}; a .pem file downloads."
ask PEM_PATH "Path to the downloaded .pem file:"
if [[ -f "$PEM_PATH" ]]; then
  set_secret FIXTURES_APP_PRIVATE_KEY "$(cat "$PEM_PATH")"
  warn "Delete $PEM_PATH once it's set: the secret is the only copy CI needs."
else
  SKIPPED+=("GitHub secret FIXTURES_APP_PRIVATE_KEY (no file at $PEM_PATH: gh secret set FIXTURES_APP_PRIVATE_KEY < key.pem)")
  warn "no file at $PEM_PATH — set FIXTURES_APP_PRIVATE_KEY later"
fi

stage "GitHub — install the App on both organisations"
open_url "https://github.com/organizations/${GH_MAIN}/settings/apps"
step "Open the App → ${BOLD}Install App${RESET} → install on ${GH_MAIN}, ${BOLD}All repositories${RESET}."
step "Install it on ${GH_OTHER} the same way."
pause "Press Enter once it's installed on both"

stage "GitLab — two groups"
say "The GitLab Fixtures live in two gitlab.com groups the project owns: one stays on Free,"
say "the other is the one to put forward for GitLab for Open Source."
open_url "https://gitlab.com/groups/new#create-group-pane"
step "Group name and URL: ${BOLD}${GL_FREE}${RESET}, visibility ${BOLD}Public${RESET}."
step "Then a second group: ${BOLD}${GL_OSS}${RESET}, Public."
note "If a name is taken, change NAMESPACES.gitlab in test/live/fixtures.ts to match."
pause "Press Enter once both groups exist"

stage "GitLab — a reading token for CI"
say "CI reads the public GitLab Fixtures with a bot account's token. Group access tokens"
say "would be better, but gitlab.com offers them only on Premium, which the Free group isn't."
step "Sign up a gitlab.com account for the project, under a project address — not a person's."
open_url "https://gitlab.com/-/user_settings/personal_access_tokens"
step "Signed in as that account: Add new token → name issue-map-fixtures-ci → scope ${BOLD}read_api${RESET} only."
note "gitlab.com tokens expire within a year: set a reminder to renew this one."
ask_secret FIXTURES_GITLAB_TOKEN "Paste the token:"
set_secret FIXTURES_GITLAB_TOKEN "$FIXTURES_GITLAB_TOKEN"

stage "GitLab for Open Source"
say "Blocks Links and epics need a licensed tier. GitLab for Open Source can license ${GL_OSS}."
warn "It asks for a public project under an OSI-approved licence: this repository needs both first."
open_url "https://about.gitlab.com/solutions/open-source/join/"
step "Apply for the ${BOLD}${GL_OSS}${RESET} group."
step "Once GitLab answers, record the outcome in docs/fixtures.md under 'GitLab for Open Source':"
step "the date, the tier granted, and which tiers it does and doesn't unlock."
pause "Press Enter once you've applied (or to come back to it later)"

stage "Seed the Fixtures"
say "The seeder makes the Projects, Issues, Links and Closing Requests test/live/fixtures.ts declares."
say "It writes with your own gh and glab logins, which need to own the organisations and groups."
say "It deletes nothing, and a second run writes nothing."
if confirm "Seed the GitHub Fixture now (node scripts/fixtures/seed.ts github)?"; then
  node scripts/fixtures/seed.ts github || SKIPPED+=("seeding github (re-run: node scripts/fixtures/seed.ts github)")
fi
if confirm "Seed the GitLab Free Fixture now (node scripts/fixtures/seed.ts gitlab-free)?"; then
  node scripts/fixtures/seed.ts gitlab-free || SKIPPED+=("seeding gitlab-free (re-run: node scripts/fixtures/seed.ts gitlab-free)")
fi
if confirm "Has GitLab for Open Source licensed ${GL_OSS}, so the licensed Fixture can be seeded?"; then
  # The nightly reads take it in only once it's seeded, or every night fails on it.
  if node scripts/fixtures/seed.ts gitlab-oss; then
    set_var ISSUE_MAP_LIVE "github,gitlab-free,gitlab-oss"
  else
    SKIPPED+=("seeding gitlab-oss (re-run: node scripts/fixtures/seed.ts gitlab-oss, then set the ISSUE_MAP_LIVE variable to github,gitlab-free,gitlab-oss)")
  fi
else
  SKIPPED+=("seeding gitlab-oss, once GitLab for Open Source licenses ${GL_OSS}: node scripts/fixtures/seed.ts gitlab-oss")
fi
pause

stage "Read them back"
say "The live reads check the adapters read exactly what was seeded."
if confirm "Run them now with your own logins (ISSUE_MAP_LIVE=github,gitlab-free npm run test:live)?"; then
  ISSUE_MAP_LIVE=github,gitlab-free npm run test:live || SKIPPED+=("the live reads failed: see the output above")
  pause
fi

stage "CI — the nightly reads and the licence gate"
say "Licensed self-managed GitLab stays stood in for until GitLab agrees in writing to a"
say "self-generated test licence in public CI (ADR 0004): the version matrix runs EE unlicensed."
set_var GITLAB_LICENCE_AGREED "false"
if confirm "Start the nightly live reads once now, as CI runs them (gh workflow run live.yml)?"; then
  gh workflow run live.yml || SKIPPED+=("starting the Live workflow: gh workflow run live.yml")
  note "Follow it with: gh run watch"
  pause
fi

finish
